// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function FetchLocalIps():Promise<Array<data.Ip>>;

export function IsHostAlive(arg1:string):Promise<boolean>;

export function ResolveHostname(arg1:string):Promise<string>;
