// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLocalIp() {
  return window['go']['network']['NetworkFunctions']['FetchLocalIp']();
}

export function IsHostAlive(arg1) {
  return window['go']['network']['NetworkFunctions']['IsHostAlive'](arg1);
}

export function ResolveHostname(arg1) {
  return window['go']['network']['NetworkFunctions']['ResolveHostname'](arg1);
}
