// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function ChangeBranch(arg1:string,arg2:string):Promise<void>;

export function CloneRepo(arg1:string,arg2:string):Promise<void>;

export function CreateCommit(arg1:data.CreateCommit):Promise<void>;

export function GetCommitDiff(arg1:string,arg2:string,arg3:string):Promise<Array<data.CommitDiff>>;

export function GetGitDirs():Promise<Array<data.File>>;

export function GetGitTokens():Promise<Array<string>>;

export function GetGitUser():Promise<data.GitUser>;

export function GetIndexedRepos():Promise<Array<data.File>>;

export function GetRemoteRepos():Promise<Array<data.RemoteRepo>>;

export function GetRepo(arg1:string):Promise<data.Repo>;

export function PullFromOrigin(arg1:string):Promise<void>;

export function PushToOrigin(arg1:string):Promise<void>;
