// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeBranch(arg1, arg2) {
  return window['go']['git']['GitFunctions']['ChangeBranch'](arg1, arg2);
}

export function CloneRepo(arg1, arg2) {
  return window['go']['git']['GitFunctions']['CloneRepo'](arg1, arg2);
}

export function CreateCommit(arg1) {
  return window['go']['git']['GitFunctions']['CreateCommit'](arg1);
}

export function GetGitDirs() {
  return window['go']['git']['GitFunctions']['GetGitDirs']();
}

export function GetGitTokens() {
  return window['go']['git']['GitFunctions']['GetGitTokens']();
}

export function GetGitUser() {
  return window['go']['git']['GitFunctions']['GetGitUser']();
}

export function GetIndexedRepos() {
  return window['go']['git']['GitFunctions']['GetIndexedRepos']();
}

export function GetRemoteRepos() {
  return window['go']['git']['GitFunctions']['GetRemoteRepos']();
}

export function GetRepo(arg1) {
  return window['go']['git']['GitFunctions']['GetRepo'](arg1);
}

export function PushToOrigin(arg1) {
  return window['go']['git']['GitFunctions']['PushToOrigin'](arg1);
}
