// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetGitTokens():Promise<Array<string>>;

export function GetRemoteRepos():Promise<data.RemoteRepo>;

export function GetRepo(arg1:string):Promise<data.Repo>;
