// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeBranch(arg1, arg2) {
  return window['go']['git']['GitFunctions']['ChangeBranch'](arg1, arg2);
}

export function GetGitDirs() {
  return window['go']['git']['GitFunctions']['GetGitDirs']();
}

export function GetGitToken() {
  return window['go']['git']['GitFunctions']['GetGitToken']();
}

export function GetGitTokens() {
  return window['go']['git']['GitFunctions']['GetGitTokens']();
}

export function GetRemoteRepos(arg1) {
  return window['go']['git']['GitFunctions']['GetRemoteRepos'](arg1);
}

export function GetRepo(arg1) {
  return window['go']['git']['GitFunctions']['GetRepo'](arg1);
}

export function SaveGitToken(arg1) {
  return window['go']['git']['GitFunctions']['SaveGitToken'](arg1);
}
