// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetDirectories(arg1:string,arg2:boolean):Promise<Array<data.Directory>>;

export function OpenFile(arg1:string):Promise<void>;
