// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectories(arg1) {
  return window['go']['directories']['DirectoriesFunctions']['GetDirectories'](arg1);
}
