// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGitDirs() {
  return window['go']['database']['DatabaseController']['GetGitDirs']();
}

export function GetGitToken() {
  return window['go']['database']['DatabaseController']['GetGitToken']();
}

export function SaveGitToken(arg1) {
  return window['go']['database']['DatabaseController']['SaveGitToken'](arg1);
}
