// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetGitDirs():Promise<Array<data.File>>;

export function GetGitToken():Promise<string>;

export function SaveGitToken(arg1:string):Promise<void>;
