// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWakaToday() {
  return window['go']['shared']['SharedFunctions']['GetWakaToday']();
}

export function KillProcess(arg1) {
  return window['go']['shared']['SharedFunctions']['KillProcess'](arg1);
}

export function Notify(arg1) {
  return window['go']['shared']['SharedFunctions']['Notify'](arg1);
}
