// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWakaToday():Promise<string>;

export function KillProcess(arg1:number):Promise<void>;

export function Notify(arg1:string):Promise<void>;
