// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function FetchLocalIp():Promise<string>;

export function GetAppState():Promise<data.AppState>;

export function GetWakaToday():Promise<string>;

export function IsHostAlive(arg1:string):Promise<boolean>;

export function KillProcess(arg1:number):Promise<void>;

export function Notify(arg1:string):Promise<void>;

export function ResolveHostname(arg1:string):Promise<string>;

export function SaveAppState(arg1:data.AppState):Promise<void>;
