// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLocalIp() {
  return window['go']['helpers']['HelperFunctions']['FetchLocalIp']();
}

export function GetAppState() {
  return window['go']['helpers']['HelperFunctions']['GetAppState']();
}

export function GetWakaToday() {
  return window['go']['helpers']['HelperFunctions']['GetWakaToday']();
}

export function IsHostAlive(arg1) {
  return window['go']['helpers']['HelperFunctions']['IsHostAlive'](arg1);
}

export function KillProcess(arg1) {
  return window['go']['helpers']['HelperFunctions']['KillProcess'](arg1);
}

export function Notify(arg1) {
  return window['go']['helpers']['HelperFunctions']['Notify'](arg1);
}

export function ResolveHostname(arg1) {
  return window['go']['helpers']['HelperFunctions']['ResolveHostname'](arg1);
}

export function SaveAppState(arg1) {
  return window['go']['helpers']['HelperFunctions']['SaveAppState'](arg1);
}
