// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileSystems() {
  return window['go']['home']['HomeFunctions']['GetFileSystems']();
}

export function GetSystemProcesses() {
  return window['go']['home']['HomeFunctions']['GetSystemProcesses']();
}

export function GetSystemResources() {
  return window['go']['home']['HomeFunctions']['GetSystemResources']();
}

export function GetUserMeta() {
  return window['go']['home']['HomeFunctions']['GetUserMeta']();
}
