// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetFileSystems():Promise<Array<data.DiskStats>>;

export function GetSystemProcesses():Promise<Array<data.Process>>;

export function GetSystemResources():Promise<data.SystemResources>;

export function GetUserMeta():Promise<data.UserMeta>;
