// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGitDirs() {
  return window['go']['main']['App']['GetGitDirs']();
}

export function GetRepo(arg1) {
  return window['go']['main']['App']['GetRepo'](arg1);
}

export function GetSystemStat() {
  return window['go']['main']['App']['GetSystemStat']();
}

export function GetWakaToday() {
  return window['go']['main']['App']['GetWakaToday']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function Notify(arg1) {
  return window['go']['main']['App']['Notify'](arg1);
}
