// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function GetSystemStat():Promise<data.SystemStats>;

export function Notify(arg1:string):Promise<void>;
