// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeBranch(arg1, arg2) {
  return window['go']['main']['App']['ChangeBranch'](arg1, arg2);
}

export function CloneRepo(arg1, arg2) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2);
}

export function GetFileSystems() {
  return window['go']['main']['App']['GetFileSystems']();
}

export function GetGitDirs() {
  return window['go']['main']['App']['GetGitDirs']();
}

export function GetGitTokens() {
  return window['go']['main']['App']['GetGitTokens']();
}

export function GetGitUser() {
  return window['go']['main']['App']['GetGitUser']();
}

export function GetRemoteRepos() {
  return window['go']['main']['App']['GetRemoteRepos']();
}

export function GetRepo(arg1) {
  return window['go']['main']['App']['GetRepo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemProcesses() {
  return window['go']['main']['App']['GetSystemProcesses']();
}

export function GetSystemResources() {
  return window['go']['main']['App']['GetSystemResources']();
}

export function GetUserMeta() {
  return window['go']['main']['App']['GetUserMeta']();
}

export function GetWakaToday() {
  return window['go']['main']['App']['GetWakaToday']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function Notify(arg1) {
  return window['go']['main']['App']['Notify'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
