// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemStat() {
  return window['go']['main']['App']['GetSystemStat']();
}

export function Notify(arg1) {
  return window['go']['main']['App']['Notify'](arg1);
}
